[package]
name = "usj_captcha_bypas"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wait-timeout = "0.2.0"
json = "0.12.4"
image = "0.23.14"
hex = "0.4.3"
